In [19]:
import pandas as pd
df = pd.read_csv('C:/Users/dhyan/OneDrive/Desktop/Data Analytics Project folder/Cyclistic trip data/Summary exports/cyclistic_combined.csv')

In [20]:
df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,ride_length,day_of_week,Unnamed: 15,Unnamed: 16,Unnamed: 17
0,058547FC0510C3B1,classic_bike,01-01-2023 23:48,01-01-2023 23:55,Millennium Park,13008,Dearborn St & Erie St,13045,41.880747,-87.624542,41.893856,-87.629719,member,00:06:16,1,0.004861,NaN,NaN
1,044C0735043528FC,classic_bike,04-01-2023 00:55,04-01-2023 01:32,Theater on the Lake,TA1308000001,State St & 33rd St,21213,41.926000,-87.630926,41.834582,-87.626291,member,00:36:32,4,0.025694,mean_ride_length_member,00:15:13
2,05D2AC6002940844,classic_bike,04-01-2023 17:06,04-01-2023 17:11,Canal St & Adams St,13011,Columbus Dr & Randolph St,13263,41.879670,-87.640034,41.884243,-87.619093,member,00:04:43,4,0.003472,mean_ride_length_casual,00:28:45
3,052378FC009CD65F,docked_bike,05-01-2023 04:46,05-01-2023 04:55,Kingsbury St & Kinzie St,KA1503000043,Theater on the Lake,TA1308000001,41.889162,-87.638704,41.926340,-87.630530,member,00:09:23,5,0.006250,NaN,NaN
4,053C9FA0012E2B7D,classic_bike,05-01-2023 22:24,05-01-2023 23:12,Kingsbury St & Kinzie St,KA1503000043,Broadway & Barry Ave,13137,41.889281,-87.638504,41.937622,-87.644112,casual,00:47:30,5,0.033333,max_ride_length_member,01:37:00

In [21]:
df = df.dropna(axis =1, how="all")   #to drop all extra null columns

In [22]:
df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,ride_length,day_of_week,Unnamed: 15,Unnamed: 16,Unnamed: 17
0,058547FC0510C3B1,classic_bike,01-01-2023 23:48,01-01-2023 23:55,Millennium Park,13008,Dearborn St & Erie St,13045,41.880747,-87.624542,41.893856,-87.629719,member,00:06:16,1,0.004861,NaN,NaN
1,044C0735043528FC,classic_bike,04-01-2023 00:55,04-01-2023 01:32,Theater on the Lake,TA1308000001,State St & 33rd St,21213,41.926000,-87.630926,41.834582,-87.626291,member,00:36:32,4,0.025694,mean_ride_length_member,00:15:13
2,05D2AC6002940844,classic_bike,04-01-2023 17:06,04-01-2023 17:11,Canal St & Adams St,13011,Columbus Dr & Randolph St,13263,41.879670,-87.640034,41.884243,-87.619093,member,00:04:43,4,0.003472,mean_ride_length_casual,00:28:45
3,052378FC009CD65F,docked_bike,05-01-2023 04:46,05-01-2023 04:55,Kingsbury St & Kinzie St,KA1503000043,Theater on the Lake,TA1308000001,41.889162,-87.638704,41.926340,-87.630530,member,00:09:23,5,0.006250,NaN,NaN
4,053C9FA0012E2B7D,classic_bike,05-01-2023 22:24,05-01-2023 23:12,Kingsbury St & Kinzie St,KA1503000043,Broadway & Barry Ave,13137,41.889281,-87.638504,41.937622,-87.644112,casual,00:47:30,5,0.033333,max_ride_length_member,01:37:00

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ride_id             500 non-null    object
 1   rideable_type       500 non-null    object
 2   started_at          500 non-null    object
 3   ended_at            500 non-null    object
 4   start_station_name  500 non-null    object
 5   start_station_id    500 non-null    object
 6   end_station_name    500 non-null    object
 7   end_station_id      500 non-null    object
 8   start_lat           500 non-null    float64
 9   start_lng           500 non-null    float64
 10  end_lat             500 non-null    float64
 11  end_lng             500 non-null    float64
 12  member_casual       500 non-null    object
 13  ride_length         500 non-null    object
 14  day_of_week         500 non-null    int64
 15  Unnamed: 15         500 non-null    float64
 16  Unnamed: 16         10 non-null     object
 17  Unnamed: 17         10 non-null     object
dtypes: float64(5), int64(1), object(12)
memory usage: 70.4+ KB

In [24]:
df.describe(include = "all")

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,ride_length,day_of_week,Unnamed: 15,Unnamed: 16,Unnamed: 17
count,500,500,500,500,500,500,500,500,500.000000,500.000000,500.000000,500.000000,500,500,500.0,500.000000,10,10
unique,500,3,499,499,15,15,15,15,NaN,NaN,NaN,NaN,2,440,NaN,NaN,10,10
top,058547FC0510C3B1,classic_bike,12-08-2023 21:03,25-12-2023 21:32,Broadway & Barry Ave,13137,Dearborn St & Erie St,13045,NaN,NaN,NaN,NaN,member,00:05:53,NaN,NaN,mean_ride_length_member,00:15:13
freq,1,280,2,2,41,41,44,44,NaN,NaN,NaN,NaN,318,4,NaN,NaN,1,1
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41.894889,-87.629624,41.894630,-87.629076,NaN,NaN,4.0,0.013988,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.022495,0.009760,0.021073,0.009806,NaN,NaN,2.0,0.012438,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41.834291,-87.644589,41.834236,-87.644592,NaN,NaN,1.0,0.002778,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41.882613,-87.638573,41.884357,-87.638148,NaN,NaN,2.0,0.006250,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41.892316,-87.630754,41.892510,-87.630482,NaN,NaN,4.0,0.010417,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41.903274,-87.623726,41.903052,-87.623601,NaN,NaN,6.0,0.017361,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41.938078,-87.611567,41.938052,-87.611549,NaN,NaN,7.0,0.098611,NaN,NaN

In [25]:
df.isnull().sum()

ride_id                 0
rideable_type           0
started_at              0
ended_at                0
start_station_name      0
start_station_id        0
end_station_name        0
end_station_id          0
start_lat               0
start_lng               0
end_lat                 0
end_lng                 0
member_casual           0
ride_length             0
day_of_week             0
Unnamed: 15             0
Unnamed: 16           490
Unnamed: 17           490
dtype: int64

In [26]:
# If any null value in above chart
#df['null value column name'] = df.groupby('reference column')['null value column name'].transform(lambda x: x.fillna(x.median()))

In [27]:
# Code snippet to change the column names from normal to snake case
# df.columns = df.columns.str.lower()
#df.columns = df.columns.str.replace(' ','_')

In [28]:
# cresting a column age_group
#labels = ['young_adult', 'Adult', 'Middle_aged', 'Senior']
#df['age_group'] = pd.qcut(df['age],q = 4, labels = labels)
#qcut = splits age into 4 equal sized groups based on data distribution and assigns the labels given above

In [29]:
#Step 1: Load and trim ghost columns(my file has 16,300 empty extra columns)
df = pd.read_csv('C:/Users/dhyan/OneDrive/Desktop/Data Analytics Project folder/Cyclistic trip data/Summary exports/cyclistic_combined.csv',low_memory = False)
df = df[df.columns[:15]]  #keeps only real 15 columns

In [30]:
#Step 2: Convert ride_length(HH:MM:SS text) to seconds
df['ride_length_sec'] = pd.to_timedelta(df['ride_length']).dt.total_seconds()

In [33]:
#Step 3: Group by member_casual and calculate all metrics at once 
summary = df.groupby('member_casual').agg(
    mean_ride_length=('ride_length_sec','mean'),
    max_ride_length=('ride_length_sec','max'),
    median_ride_length=('ride_length_sec','median'),
    mode_day_of_week=('day_of_week', lambda x: x.mode()[0]),
    total_rides = ('ride_length_sec','count')
)

In [34]:
#Step 4: Convert seconds back to HH:MM:SS for redable output
for col in ['mean_ride_length','max_ride_length','median_ride_length']:
    summary[col] = pd.to_timedelta(summary[col],unit='s')
print(summary)

                       mean_ride_length max_ride_length  \
member_casual
casual        0 days 00:28:48.016483516 0 days 02:21:15
member        0 days 00:15:12.169811321 0 days 01:36:31

                  median_ride_length  mode_day_of_week  total_rides
member_casual
casual               0 days 00:21:35                 7          182
member        0 days 00:11:23.500000                 1          318